#!/bin/bash
depinst()
{
        echo -e "\e[93m[Installing pygeoip]"
	pip install pygeoip
	echo -e "\e[93m[Fetching GeoLiteCity]"
        wget -N -q http://geolite.maxmind.com/download/geoip/database/GeoLiteCity.dat.gz
        gzip -d GeoLiteCity.dat.gz
}
addpath()
{
	mkdir -p ~/bin;
	mkdir -p ~/scripts;
	mkdir -p ~/scripts/geo_lock ;
	mv geo_lock ~/bin/ || :;
	chmod +x ~/bin/geo_lock;
	mv geo_lock.py ~/scripts/geo_lock/ || :;
	chmod +x ~/scripts/geo_lock/geo_lock.py;
	mv GeoLiteCity.dat ~/scripts/geo_lock || :;
	export PATH=$PATH:~/bin
	~/.profile
}
getfiles()
{
	if [ ! -f "geo_lock" ]; then
		wget -q https://raw.githubusercontent.com/iboyperson/geo_lock/master/geo_lock
	fi
	if [ ! -f "geo_lock.py" ]; then
        	wget -q https://raw.githubusercontent.com/iboyperson/geo_lock/master/geo_lock.py
	fi
}
getfiles
echo -e "\e[32m\c"
read -p "Do you want to install dependencies?(y/n) " DEP
echo -e "\e[91m\c"
if [ "$DEP" = "y" ]; then
        echo -e "\e[93m[Installing dependencies]"
	echo -e "\e[91m\c"
        depinst >/dev/null
fi
echo -e "\e[32m\c"
read -p "Do you want to add Geo_Lock to path?(y/n) " PTH
echo -e "\e[91m\c"
if [ "$PTH" = "y" ]; then
	addpath >/dev/null
else
	exit
fi
echo -e "\e[93m[Cleaning Up]"
if [ -f "geo_lock" ]; then
	rm geo_lock;
fi
if [ -f "geo_lock.py" ]; then
        rm geo_lock.py;
fi
if [ -f "GeoLitCity.dat" ]; then
        rm GeoLiteCity.dat;
fi


