#!/usr/bin/env python
import sys
import os
import maxman
import dataman

# Py2/3 compatibility
# Python3 renamed raw_input to input
try:
    input = raw_input
except NameError:
    pass

try:
	ip = str(sys.argv[1])
except:
	ip = raw_input('\x1b[1;33m' + 'Input IP:' + '\x1b[0m' + " ")

def get_banner():
	ascii = open('banner.txt', 'r')
	asciicont = ascii.read()
	return ('\x1b[1;32m' + asciicont + '\x1b[0m')

maxman.maxdbcheck(ip)
print ('\x1b[1;33m' + '[Downloading Databases]' + '\x1b[0m')
data = dataman.getdata(ip)
os.system('clear')
try:
	try:
		#Prints the GEO_LOCK ascii art
		print get_banner()
		print ('\x1b[1;33m'+"IP:" + '\x1b[0m' + '               ' + data['ip'])
		print ('\x1b[1;33m'+"Host:" + '\x1b[0m' + '             ' + data['host'])
		print ('\x1b[1;33m'+"City:" + '\x1b[0m' + '             ' + data['city'])
		print ('\x1b[1;33m'+"Region:" + '\x1b[0m' + '           ' + data['region'])
		print ('\x1b[1;33m'+"County:" + '\x1b[0m' + '           ' + data['country'])
		print ('\x1b[1;33m'+"Continent:" + '\x1b[0m' + '        ' + data['continent'])
		print ('\x1b[1;33m'+"Geo Coordinates:" + '\x1b[0m' + '  ' + data['geoloc'])
		print ('\x1b[1;33m'+"Postal Code:" + '\x1b[0m' + '      ' + data['zip_code'])
		print ('\x1b[1;33m'+"Area Code:" + '\x1b[0m' + '        ' + data['area_code'])
		print ('\x1b[1;33m'+"DMA Code:" + '\x1b[0m' + '         ' + data['dma_code'])
		print ('\x1b[1;33m'+"Time Zone:" + '\x1b[0m' + '        ' + data['time_zone'])
		print ('\x1b[1;33m'+"ISP:" + '\x1b[0m' + '              ' + data['isp'])
		print ('\x1b[1;33m'+"Organization:" + '\x1b[0m' + '     ' + data['org'])
		print ('\x1b[1;33m'+"ASN:" + '\x1b[0m' + '              ' + data['asn'])
		print ('\x1b[1;33m'+"Using Proxy?:" + '\x1b[0m' + '     ' + data['proxy'])
		print ('\x1b[1;33m'+"On Mobile?:" + '\x1b[0m' + '       ' + data['mobile'])

	except KeyboardInterrupt:
		print(' ')
except NameError:
	print('Exiting...')
